export default function Attributes() {
  return [
    {
      name: "Mary",
      hairColor: "black",
      hairStyle: "long",
      glasses: false,
      gender: "female",
      hat: false,
      accessories: "headband",
      skinTone: "tanned",
      expression: "serious",
    },
    {
      name: "Monique",
      hairColor: "black",
      hairStyle: "curly",
      glasses: true,
      gender: "female",
      hat: false,
      accessories: null,
      skinTone: "tanned",
      expression: "smiling",
    },
    {
      name: "Paul",
      hairColor: "red",
      hairStyle: "curly",
      glasses: true,
      gender: "male",
      hat: false,
      accessories: "beard",
      skinTone: "light",
      expression: "smiling",
    },
    {
      name: "Peter",
      hairColor: "brown",
      hairStyle: "short",
      glasses: false,
      gender: "male",
      hat: false,
      accessories: "freckles",
      skinTone: "light",
      expression: "smiling",
    },
    {
      name: "Rebecca",
      hairColor: "brown",
      hairStyle: "long",
      glasses: false,
      gender: "female",
      hat: true,
      hatColour: "red with white pompom",
      accessories: "scarf",
      skinTone: "light",
      expression: "neutral",
    },
    {
      name: "Rupert",
      hairColor: "red",
      hairStyle: "short",
      glasses: false,
      gender: "male",
      hat: true,
      hatColour: "green",
      accessories: null,
      skinTone: "light",
      expression: "smiling",
    },
    {
      name: "Sarah",
      hairColor: "blonde",
      hairStyle: "long",
      glasses: false,
      gender: "female",
      hat: false,
      accessories: null,
      skinTone: "light",
      expression: "smiling",
    },
    {
      name: "Wildcard",
      hairColor: "gray",
      hairStyle: "short",
      glasses: true,
      gender: "male",
      hat: false,
      accessories: "headphones beard",
      skinTone: "light",
      expression: "neutral",
    },
    {
      name: "Yan",
      hairColor: "brown",
      hairStyle: "short",
      glasses: false,
      gender: "male",
      hat: false,
      accessories: null,
      skinTone: "tanned",
      expression: "neutral",
    },
    {
      name: "Yvette",
      hairColor: "red",
      hairStyle: "curly",
      glasses: true,
      gender: "female",
      hat: false,
      accessories: "earrings",
      skinTone: "light",
      expression: "smiling",
    },
  ];
}
